<?php
/**
 * ACF Field Group - Sections
 * Programmatically register the Sections field group for Posts and Pages
 */

if (!function_exists('acf_add_local_field_group')) {
    return;
}

acf_add_local_field_group([
    'key' => 'group_695bba3e7d7a8',
    'title' => 'Sections',
    'fields' => [
        [
            'key' => 'field_695bbf7e3589e',
            'label' => 'Sections',
            'name' => 'sections',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'row',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Add Row',
            'rows_per_page' => 20,
            'sub_fields' => [
                [
                    'key' => 'field_695bc0023589f',
                    'label' => 'Title',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_695bbf7e3589e',
                ],
                [
                    'key' => 'field_695bc01d358a0',
                    'label' => 'Box',
                    'name' => 'box',
                    'aria-label' => '',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layouts' => [
                        'layout_695bc03b1cc10' => [
                            'key' => 'layout_695bc03b1cc10',
                            'name' => 'title_subtitle_and_text',
                            'label' => 'Title, subtitle and text',
                            'display' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_695bf160b5858',
                                    'label' => 'Visible',
                                    'name' => 'visible',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 1,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ],
                                [
                                    'key' => 'field_695bc1bb939d5',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ],
                                [
                                    'key' => 'field_695bc1c3939d6',
                                    'label' => 'Subtitle',
                                    'name' => 'subtitle',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ],
                                [
                                    'key' => 'field_695bc1d0939d7',
                                    'label' => 'Text',
                                    'name' => 'text',
                                    'aria-label' => '',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'rows' => '',
                                    'placeholder' => '',
                                    'new_lines' => '',
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        'layout_695bc3c71b00e' => [
                            'key' => 'layout_695bc3c71b00e',
                            'name' => 'title_and_3_cards',
                            'label' => 'Title and 3 cards',
                            'display' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_695bf1a8b585b',
                                    'label' => 'Visible',
                                    'name' => 'visible',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 1,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ],
                                [
                                    'key' => 'field_695bc3d71b010',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ],
                                [
                                    'key' => 'field_695bc3e31b011',
                                    'label' => 'Cards',
                                    'name' => 'cards',
                                    'aria-label' => '',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'layout' => 'table',
                                    'min' => 0,
                                    'max' => 0,
                                    'collapsed' => '',
                                    'button_label' => 'Add Row',
                                    'rows_per_page' => 20,
                                    'sub_fields' => [
                                        [
                                            'key' => 'field_695bc4161b012',
                                            'label' => 'Icons',
                                            'name' => 'icons',
                                            'aria-label' => '',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'return_format' => 'url',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'allow_in_bindings' => 0,
                                            'preview_size' => 'medium',
                                            'parent_repeater' => 'field_695bc3e31b011',
                                        ],
                                        [
                                            'key' => 'field_695bc4431b013',
                                            'label' => 'Title',
                                            'name' => 'title',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'parent_repeater' => 'field_695bc3e31b011',
                                        ],
                                        [
                                            'key' => 'field_695bc44b1b014',
                                            'label' => 'Text',
                                            'name' => 'text',
                                            'aria-label' => '',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'rows' => '',
                                            'placeholder' => '',
                                            'new_lines' => '',
                                            'parent_repeater' => 'field_695bc3e31b011',
                                        ],
                                    ],
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        'layout_695be60674d3e' => [
                            'key' => 'layout_695be60674d3e',
                            'name' => 'action_button',
                            'label' => 'Action Button',
                            'display' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_695bf1e5b585c',
                                    'label' => 'Visible',
                                    'name' => 'visible',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 1,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ],
                                [
                                    'key' => 'field_695be72374d42',
                                    'label' => 'Icon',
                                    'name' => 'icon',
                                    'aria-label' => '',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'return_format' => 'url',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                    'allow_in_bindings' => 0,
                                    'preview_size' => 'medium',
                                ],
                                [
                                    'key' => 'field_695be64374d40',
                                    'label' => 'Label',
                                    'name' => 'label',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ],
                                [
                                    'key' => 'field_695be6e674d41',
                                    'label' => 'Link',
                                    'name' => 'link',
                                    'aria-label' => '',
                                    'type' => 'link',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'return_format' => 'url',
                                    'allow_in_bindings' => 0,
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        'layout_695bf583f6d26' => [
                            'key' => 'layout_695bf583f6d26',
                            'name' => 'faqs_box',
                            'label' => 'FAQs box',
                            'display' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_695bf5aaf6d29',
                                    'label' => 'Visible',
                                    'name' => 'visible',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 1,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ],
                                [
                                    'key' => 'field_695bf597f6d28',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        'layout_695c6c07b78d3' => [
                            'key' => 'layout_695c6c07b78d3',
                            'name' => 'box_rules',
                            'label' => 'Box Rules',
                            'display' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_695c784485c13',
                                    'label' => 'Visible',
                                    'name' => 'visible',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 1,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ],
                                [
                                    'key' => 'field_695c6c36b78d5',
                                    'label' => 'Cards',
                                    'name' => 'cards',
                                    'aria-label' => '',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'layout' => 'row',
                                    'min' => 0,
                                    'max' => 0,
                                    'collapsed' => '',
                                    'button_label' => 'Add Row',
                                    'rows_per_page' => 20,
                                    'sub_fields' => [
                                        [
                                            'key' => 'field_695c6c55b78d6',
                                            'label' => 'Type',
                                            'name' => 'type',
                                            'aria-label' => '',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'choices' => [
                                                'rules' => 'Rules',
                                                'ban' => 'Ban',
                                            ],
                                            'default_value' => 'rules',
                                            'return_format' => 'value',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'allow_in_bindings' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                            'create_options' => 0,
                                            'save_options' => 0,
                                            'parent_repeater' => 'field_695c6c36b78d5',
                                        ],
                                        [
                                            'key' => 'field_695c6cb0b78d7',
                                            'label' => 'Icon',
                                            'name' => 'icon',
                                            'aria-label' => '',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'return_format' => 'url',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'allow_in_bindings' => 0,
                                            'preview_size' => 'medium',
                                            'parent_repeater' => 'field_695c6c36b78d5',
                                        ],
                                        [
                                            'key' => 'field_695c6cc2b78d8',
                                            'label' => 'Title',
                                            'name' => 'title',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'parent_repeater' => 'field_695c6c36b78d5',
                                        ],
                                        [
                                            'key' => 'field_695c6cd0b78d9',
                                            'label' => 'Rows',
                                            'name' => 'rows',
                                            'aria-label' => '',
                                            'type' => 'repeater',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'layout' => 'table',
                                            'pagination' => 0,
                                            'min' => 0,
                                            'max' => 0,
                                            'collapsed' => '',
                                            'button_label' => 'Add Row',
                                            'rows_per_page' => 20,
                                            'sub_fields' => [
                                                [
                                                    'key' => 'field_695c6ce2b78da',
                                                    'label' => 'Text',
                                                    'name' => 'text',
                                                    'aria-label' => '',
                                                    'type' => 'textarea',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => [
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ],
                                                    'default_value' => '',
                                                    'maxlength' => '',
                                                    'allow_in_bindings' => 0,
                                                    'rows' => '',
                                                    'placeholder' => '',
                                                    'new_lines' => '',
                                                    'parent_repeater' => 'field_695c6cd0b78d9',
                                                ],
                                                [
                                                    'key' => 'field_695c6cfeb78db',
                                                    'label' => 'Url',
                                                    'name' => 'url',
                                                    'aria-label' => '',
                                                    'type' => 'link',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => [
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ],
                                                    'return_format' => 'url',
                                                    'allow_in_bindings' => 0,
                                                    'parent_repeater' => 'field_695c6cd0b78d9',
                                                ],
                                                [
                                                    'key' => 'field_695c6d44b78dc',
                                                    'label' => 'Inline?',
                                                    'name' => 'link_inline',
                                                    'aria-label' => '',
                                                    'type' => 'true_false',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => [
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ],
                                                    'message' => '',
                                                    'default_value' => 1,
                                                    'allow_in_bindings' => 0,
                                                    'ui' => 0,
                                                    'ui_on_text' => '',
                                                    'ui_off_text' => '',
                                                    'parent_repeater' => 'field_695c6cd0b78d9',
                                                ],
                                            ],
                                            'parent_repeater' => 'field_695c6c36b78d5',
                                        ],
                                    ],
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        'layout_695c773485c0f' => [
                            'key' => 'layout_695c773485c0f',
                            'name' => 'banlist_card',
                            'label' => 'Banlist Card',
                            'display' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_695c786065c14',
                                    'label' => 'Visible',
                                    'name' => 'visible',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 1,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ],
                                [
                                    'key' => 'field_695c77fd85c11',
                                    'label' => 'Icon',
                                    'name' => 'icon',
                                    'aria-label' => '',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'return_format' => 'url',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                    'allow_in_bindings' => 0,
                                    'preview_size' => 'medium',
                                ],
                                [
                                    'key' => 'field_695c781985c12',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'aria-label' => '',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => 'Banned Cards',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'rows' => '',
                                    'placeholder' => '',
                                    'new_lines' => '',
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        'layout_695c6d979983d' => [
                            'key' => 'layout_695c6d979983d',
                            'name' => 'links_list',
                            'label' => 'Links List',
                            'display' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_695c787e85c15',
                                    'label' => 'Visible',
                                    'name' => 'visible',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 1,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ],
                                [
                                    'key' => 'field_695c6da29983f',
                                    'label' => 'Links',
                                    'name' => 'links',
                                    'aria-label' => '',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'layout' => 'row',
                                    'min' => 0,
                                    'max' => 0,
                                    'collapsed' => '',
                                    'button_label' => 'Add Row',
                                    'rows_per_page' => 20,
                                    'sub_fields' => [
                                        [
                                            'key' => 'field_695c6dd599840',
                                            'label' => 'Icon',
                                            'name' => 'icon',
                                            'aria-label' => '',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'return_format' => 'url',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'allow_in_bindings' => 0,
                                            'preview_size' => 'medium',
                                            'parent_repeater' => 'field_695c6da29983f',
                                        ],
                                        [
                                            'key' => 'field_695c6de299841',
                                            'label' => 'Title',
                                            'name' => 'title',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'parent_repeater' => 'field_695c6da29983f',
                                        ],
                                        [
                                            'key' => 'field_695c6dea99842',
                                            'label' => 'Subtitle',
                                            'name' => 'subtitle',
                                            'aria-label' => '',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'rows' => '',
                                            'placeholder' => '',
                                            'new_lines' => '',
                                            'parent_repeater' => 'field_695c6da29983f',
                                        ],
                                        [
                                            'key' => 'field_695c6df499843',
                                            'label' => 'Url',
                                            'name' => 'url',
                                            'aria-label' => '',
                                            'type' => 'link',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'return_format' => 'url',
                                            'allow_in_bindings' => 0,
                                            'parent_repeater' => 'field_695c6da29983f',
                                        ],
                                        [
                                            'key' => 'field_695c789385c16',
                                            'label' => 'Visible',
                                            'name' => 'visible',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'message' => '',
                                            'default_value' => 1,
                                            'allow_in_bindings' => 0,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                            'parent_repeater' => 'field_695c6da29983f',
                                        ],
                                    ],
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        'layout_695d8bc19363f' => [
                            'key' => 'layout_695d8bc19363f',
                            'name' => 'about_list',
                            'label' => 'About List',
                            'display' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_695d8bc193640',
                                    'label' => 'Visible',
                                    'name' => 'visible',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'message' => '',
                                    'default_value' => 1,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ],
                                [
                                    'key' => 'field_695d8bc193641',
                                    'label' => 'People',
                                    'name' => 'people',
                                    'aria-label' => '',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'layout' => 'row',
                                    'min' => 0,
                                    'max' => 0,
                                    'collapsed' => '',
                                    'button_label' => 'Add Row',
                                    'rows_per_page' => 20,
                                    'sub_fields' => [
                                        [
                                            'key' => 'field_695d8bc193646',
                                            'label' => 'Visible',
                                            'name' => 'visible',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'message' => '',
                                            'default_value' => 1,
                                            'allow_in_bindings' => 0,
                                            'ui' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                            'parent_repeater' => 'field_695d8bc193641',
                                        ],
                                        [
                                            'key' => 'field_695d8bc193642',
                                            'label' => 'Icon',
                                            'name' => 'icon',
                                            'aria-label' => '',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'return_format' => 'url',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'allow_in_bindings' => 0,
                                            'preview_size' => 'medium',
                                            'parent_repeater' => 'field_695d8bc193641',
                                        ],
                                        [
                                            'key' => 'field_695d8bc193643',
                                            'label' => 'Title',
                                            'name' => 'title',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'parent_repeater' => 'field_695d8bc193641',
                                        ],
                                        [
                                            'key' => 'field_695d8c2893647',
                                            'label' => 'Nickname',
                                            'name' => 'nickname',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'parent_repeater' => 'field_695d8bc193641',
                                        ],
                                        [
                                            'key' => 'field_695d8bc193644',
                                            'label' => 'Subtitle',
                                            'name' => 'subtitle',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'parent_repeater' => 'field_695d8bc193641',
                                        ],
                                        [
                                            'key' => 'field_695d912bdbeea',
                                            'label' => 'Text',
                                            'name' => 'text',
                                            'aria-label' => '',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'rows' => '',
                                            'placeholder' => '',
                                            'new_lines' => '',
                                            'parent_repeater' => 'field_695d8bc193641',
                                        ],
                                        [
                                            'key' => 'field_695d8bc193645',
                                            'label' => 'Url',
                                            'name' => 'url',
                                            'aria-label' => '',
                                            'type' => 'link',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'return_format' => 'url',
                                            'allow_in_bindings' => 0,
                                            'parent_repeater' => 'field_695d8bc193641',
                                        ],
                                        [
                                            'key' => 'field_695d8c7793648',
                                            'label' => 'Profile',
                                            'name' => 'profile',
                                            'aria-label' => '',
                                            'type' => 'user',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => [
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ],
                                            'role' => '',
                                            'return_format' => 'object',
                                            'multiple' => 0,
                                            'allow_null' => 0,
                                            'allow_in_bindings' => 0,
                                            'bidirectional' => 0,
                                            'bidirectional_target' => [],
                                            'parent_repeater' => 'field_695d8bc193641',
                                        ],
                                    ],
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                        'layout_6989129bb5e56' => [
                            'key' => 'layout_6989129bb5e56',
                            'name' => 'box_html',
                            'label' => 'Box Html',
                            'display' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_698912a6b5e5a',
                                    'label' => 'html',
                                    'name' => 'html',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => [
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ],
                                    'default_value' => '',
                                    'allow_in_bindings' => 0,
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ],
                            ],
                            'min' => '',
                            'max' => '',
                        ],
                    ],
                    'min' => '',
                    'max' => '',
                    'button_label' => 'Add Row',
                    'parent_repeater' => 'field_695bbf7e3589e',
                ],
            ],
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ],
        ],
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'page',
            ],
        ],
    ],
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
]);
